### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nodirhajiev** [developeranaz/qbittorrent-to-rclone-heroku-beta#4]
After deploying app, it's not working

Scripted By DevAnaZ
2022-01-09T14:39:40.356952+00:00 app[web.1]: Orgin repository : https://github.com/developeranaz/qbittorrent-to-rclone-heroku
2022-01-09T14:39:40.389328+00:00 app[web.1]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-01-09T14:39:40.389570+00:00 app[web.1]:                                  Dload  Upload   Total   Spent    Left  Speed
2022-01-09T14:39:40.500638+00:00 app[web.1]: 
2022-01-09T14:39:41.110201+00:00 heroku[web.1]: State changed from starting to up

Error message

**Comment by developeranaz** [comment]
i had checked and its working

**Comment by developeranaz** [comment]
check your config

**Comment by nodirhajiev** [comment]
RCLONE_CONFIG_IN_RAW_URL = https://gist.githubusercontent.com/nodirhajiev/xxxxxxxx/raw/rclone.conf

Like this?

**Comment by nodirhajiev** [comment]
> check your config vars or try deploy using [![Deploy](https://camo.githubusercontent.com/6979881d5a96b7b18a057083bb8aeb87ba35fc279452e29034c1e1c49ade0636/68747470733a2f2f7777772e6865726f6b7563646e2e636f6d2f6465706c6f792f627574746f6e2e737667)](https://dashboard.heroku.com/new?template=https://github.com/dev-extended/developeranaz-780636CE89D20522271DF0805C35D433EF827019F263D4A875FFC762D8F4F039) this button

i have did by clicking button

**Comment by developeranaz** [comment]
> > check your config vars or try deploy using [![Deploy](https://camo.githubusercontent.com/6979881d5a96b7b18a057083bb8aeb87ba35fc279452e29034c1e1c49ade0636/68747470733a2f2f7777772e6865726f6b7563646e2e636f6d2f6465706c6f792f627574746f6e2e737667)](https://dashboard.heroku.com/new?template=https://github.com/dev-extended/developeranaz-780636CE89D20522271DF0805C35D433EF827019F263D4A875FFC762D8F4F039) this button
> 
> i have did by clicking button

try restart dynos

**Comment by developeranaz** [comment]
if it didn't worked then click on  [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/dev-extended/developeranaz-780636CE89D20522271DF0805C35D433EF827019F263D4A875FFC762D8F4F039)  this button 
2. don't change  any values same as above and deploy. 
3. the webapp will works after that go to heroku deployed app settingsand change your config vars.

![Screenshot_20220109_203721_com brave browser](https://user-images.githubusercontent.com/71500526/148688194-f8d8e08a-140e-4452-90ff-79df02b25d75.jpg)

**Comment by nodirhajiev** [comment]
> if it didn't worked then click on [![Deploy](https://camo.githubusercontent.com/6979881d5a96b7b18a057083bb8aeb87ba35fc279452e29034c1e1c49ade0636/68747470733a2f2f7777772e6865726f6b7563646e2e636f6d2f6465706c6f792f627574746f6e2e737667)](https://dashboard.heroku.com/new?template=https://github.com/dev-extended/developeranaz-780636CE89D20522271DF0805C35D433EF827019F263D4A875FFC762D8F4F039) this button 2. don't change any values same as defult (check image below) and deploy. 3. the webapp will works after that go to heroku deployed app settingsand change your config vars.
> 
> ![Screenshot_20220109_203721_com brave browser](https://user-images.githubusercontent.com/71500526/148688194-f8d8e08a-140e-4452-90ff-79df02b25d75.jpg)

Did like this, it worked without any vars. After filling vars it's not working again

**Comment by developeranaz** [comment]
try some simple password and username 
don't use space in config vars

**Comment by nodirhajiev** [comment]
> try some simple password and username don't use space in config vars

Did as you said, it's not working

**Comment by nodirhajiev** [comment]
Could you do tutorial step by step?

**Comment by nodirhajiev** [comment]
> try some simple password and username don't use space in config vars

HTTP ERROR 401 says
